### ISSUE TITLE
Week 2 - How Mozilla earn money?

### ISSUE THREAD

**Issue by letientai299** [duytruong/weekly-question#4]
Consider that:
- Firefox is free and open source.
- Mozilla develops and maintains lot of open source, standards, web page (MSDN).
- They have a company and hire staff to build Firefox.
- We have never ever donate for Mozilla, and a lot of people out there never done this. 

How could they find money to maintain such a thing like Firefox?

Edit: typo

**Comment by duytruong** [comment]
- When you search something, Firefox uses Google to search, and Google pays for them.
- Some organization use Firefox ESR (Extended Support Release), I think they pay for Mozilla.

p/s: there is a typo error in your post: `Frefox is free and open source.` -> `Firefox`

**Comment by letientai299** [comment]
Still not satisfy. I believe there much be a more stable way for them to keep the company/organization alive. Will investigate more on this.

**Comment by letientai299** [comment]
After researching, here's what I found:
- Mozilla revenue comes from search providers (mostly Google, beside Yahoo, Yandex, Baidu,...) and donation.
- ESR release doesn't cost anything. 

That's really impressive on how many things Mozilla has built as a non-profit corporation.
